const initialState = {
  creditLimit: '',
  tempCredit: '',
  until: '',
  settle: '',
  straightEarlyLimit: '',
  overnightLimit: '',
  maxContestPayout: '',
  maxContestOdds: '',
  minContestOdds: '',
  allGenlLimMin: '',
  allGenlLimMax: '',
  allGenlLimFactor: '',
  allGenlLimPerGame: '',
  straightGenLimMin: '',
  straightGenLimMax: '',
  straightGenLimFactor: '',
  straightGenLimPerGame: '',
  liveSportsGenLimMin: '',
  liveSportsGenLimMax: '',
  liveSportsGenLimFactor: '',
  liveSportsGenLimPerGame: '',
  parlayGenLimMin: '',
  parlayGenLimMax: '',
  parlayGenLimFactor: '',
  parlayGenLimPerGame: '',
  teaserGenLimMin: '',
  teaserGenLimFactor: '',
  teaserGenLimPerGame: '',
  IfBetGenLimMin: '',
  IfBetGenLimMax: '',
  IfBetGenLimFactor: '',
  IfBetGenLimPerGame: '',
  HorsesGenLimMin: '',
  HorsesGenLimMax: '',
  HorsesGenLimFactor: '',
  HorsesGenLimPerGame: '',
};

export default initialState;
