const ClientHistoryActionTypes = {
  FETCH_CLIENT_HISTORY_REQUEST  : 'FETCH_CLIENT_HISTORY_REQUEST',
  FETCH_CLIENT_HISTORY_SUCCESS  : 'FETCH_CLIENT_HISTORY_SUCCESS',
  FETCH_CLIENT_HISTORY_FAILURE  : 'FETCH_CLIENT_HISTORY_FAILURE',
};

export default ClientHistoryActionTypes;
