const HorsesBettibgsService = {
  FETCH_HORSES_BETTINGS_REQUEST: 'FETCH_HORSES_BETTINGS_REQUEST',
  FETCH_HORSES_BETTINGS_SUCCESS: 'FETCH_HORSES_BETTINGS_SUCCESS',
  FETCH_HORSES_BETTINGS_FAILURE: 'FETCH_HORSES_BETTINGS_FAILURE',
};

export default HorsesBettibgsService;
