const AccountsClosedTypes = {
  FETCH_ACCOUNTS_CLOSED_REQUEST: 'FETCH_ACCOUNTS_CLOSED_REQUEST',
  FETCH_ACCOUNTS_CLOSED_SUCCESS: 'FETCH_ACCOUNTS_CLOSED_SUCCESS',
  FETCH_ACCOUNTS_CLOSED_FAILURE: 'FETCH_ACCOUNTS_CLOSED_FAILURE',
  TOGGLE_ACCOUNTS_CLOSED: 'TOGGLE_ACCOUNTS_CLOSED',
};

export default AccountsClosedTypes;
