const LiveMarketsTypes = {
  FETCH_LIVE_MARKETS_REQUEST  : 'FETCH_LIVE_MARKETS_REQUEST',
  FETCH_LIVE_MARKETS_SUCCESS  : 'FETCH_LIVE_MARKETS_SUCCESS',
  FETCH_LIVE_MARKETS_FAILURE  : 'FETCH_LIVE_MARKETS_FAILURE',
};

export default LiveMarketsTypes;
