const DistributionTypes = {
  FETCH_DISTRIBUTION_REQUEST  : 'FETCH_DISTRIBUTION_REQUEST',
  FETCH_DISTRIBUTION_SUCCESS  : 'FETCH_DISTRIBUTION_SUCCESS',
  FETCH_DISTRIBUTION_FAILURE  : 'FETCH_DISTRIBUTION_FAILURE',
};

export default DistributionTypes;
