const ActivePlayersTypes = {
  FETCH_ACTIVE_PLAYERS_REQUEST: 'FETCH_ACTIVE_PLAYERS_REQUEST',
  FETCH_ACTIVE_PLAYERS_SUCCESS: 'FETCH_ACTIVE_PLAYERS_SUCCESS',
  FETCH_ACTIVE_PLAYERS_FAILURE: 'FETCH_ACTIVE_PLAYERS_FAILURE',
  TOGGLE_ACTIVE_PLAYERS: 'TOGGLE_ACTIVE_PLAYERS',
};

export default ActivePlayersTypes;
