const BalanceActionTypes = {
  FETCH_BALANCE_REQUEST  : 'FETCH_BALANCE_REQUEST',
  FETCH_BALANCE_SUCCESS  : 'FETCH_BALANCE_SUCCESS',
  FETCH_BALANCE_FAILURE  : 'FETCH_BALANCE_FAILURE',
};

export default BalanceActionTypes;
