const BiggestPendingWagersTypes = {
  FETCH_BIGGEST_PENDING_WAGERS_REQUEST: 'FETCH_BIGGEST_PENDING_WAGERS_REQUEST',
  FETCH_BIGGEST_PENDING_WAGERS_SUCCESS: 'FETCH_BIGGEST_PENDING_WAGERS_SUCCESS',
  FETCH_BIGGEST_PENDING_WAGERS_FAILURE: 'FETCH_BIGGEST_PENDING_WAGERS_FAILURE',
};

export default BiggestPendingWagersTypes;
