const PendingTypes = {
  FETCH_PENDING_REQUEST  : 'FETCH_PENDING_REQUEST',
  FETCH_PENDING_SUCCESS  : 'FETCH_PENDING_SUCCESS',
  FETCH_PENDING_FAILURE  : 'FETCH_PENDING_FAILURE',
};

export default PendingTypes;
