const ClientControlDetailLimits = {
  FETCH_CLIENT_DETAIL_LIMITS_REQUEST  : 'FETCH_CLIENT_DETAIL_LIMITS_REQUEST',
  FETCH_CLIENT_DETAIL_LIMITS_SUCCESS  : 'FETCH_CLIENT_DETAIL_LIMITS_SUCCESS',
  FETCH_CLIENT_DETAIL_LIMITS_FAILURE  : 'FETCH_CLIENT_DETAIL_LIMITS_FAILURE',
};

export default ClientControlDetailLimits;
