const PositionGamesTypes = {
  FETCH_POSITION_GAMES_REQUEST  : 'FETCH_POSITION_GAMES_REQUEST',
  FETCH_POSITION_GAMES_SUCCESS  : 'FETCH_POSITION_GAMES_SUCCESS',
  FETCH_POSITION_GAMES_FAILURE  : 'FETCH_POSITION_GAMES_FAILURE',
};

export default PositionGamesTypes;
