const MyTransactionsTypes = {
  FETCH_MY_TRANSACTIONS_REQUEST: 'FETCH_MY_TRANSACTIONS_REQUEST',
  FETCH_MY_TRANSACTIONS_SUCCESS: 'FETCH_MY_TRANSACTIONS_SUCCESS',
  FETCH_MY_TRANSACTIONS_FAILURE: 'FETCH_MY_TRANSACTIONS_FAILURE',
};

export default MyTransactionsTypes;
