const HorsesTracksTypes = {
  FETCH_HORSES_TRACKS_REQUEST  : 'FETCH_HORSES_TRACKS_REQUEST',
  FETCH_HORSES_TRACKS_SUCCESS  : 'FETCH_HORSES_TRACKS_SUCCESS',
  FETCH_HORSES_TRACKS_FAILURE  : 'FETCH_HORSES_TRACKS_FAILURE',
};

export default HorsesTracksTypes;
