const SettleTypes = {
  FETCH_SETTLE_REQUEST  : 'FETCH_SETTLE_REQUEST',
  FETCH_SETTLE_SUCCESS  : 'FETCH_SETTLE_SUCCESS',
  FETCH_SETTLE_FAILURE  : 'FETCH_SETTLE_FAILURE',
};

export default SettleTypes;
