const CashierActionTypes = {
  FETCH_CASHIER_REQUEST  : 'FETCH_CASHIER_REQUEST',
  FETCH_CASHIER_SUCCESS  : 'FETCH_CASHIER_SUCCESS',
  FETCH_CASHIER_FAILURE  : 'FETCH_CASHIER_FAILURE',
};

export default CashierActionTypes;
