const PositionLiveSportsTypes = {
  FETCH_POSITION_LIVE_SPORTS_REQUEST  : 'FETCH_POSITION_LIVE_SPORTS_REQUEST',
  FETCH_POSITION_LIVE_SPORTS_SUCCESS  : 'FETCH_POSITION_LIVE_SPORTS_SUCCESS',
  FETCH_POSITION_LIVE_SPORTS_FAILURE  : 'FETCH_POSITION_LIVE_SPORTS_FAILURE',
};

export default PositionLiveSportsTypes;
