const ClientLimitsActionTypes = {
  FETCH_CLIENT_LIMITS_REQUEST  : 'FETCH_CLIENT_LIMITS_REQUEST',
  FETCH_CLIENT_LIMITS_SUCCESS  : 'FETCH_CLIENT_LIMITS_SUCCESS',
  FETCH_CLIENT_LIMITS_FAILURE  : 'FETCH_CLIENT_LIMITS_FAILURE',
};

export default ClientLimitsActionTypes;
