const LivePendingTypes = {
  FETCH_LIVE_PENDING_REQUEST  : 'FETCH_LIVE_PENDING_REQUEST',
  FETCH_LIVE_PENDING_SUCCESS  : 'FETCH_LIVE_PENDING_SUCCESS',
  FETCH_LIVE_PENDING_FAILURE  : 'FETCH_LIVE_PENDING_FAILURE',
};

export default LivePendingTypes;
