const SportsActionTypes = {
  FETCH_SPORTS_REQUEST: 'FETCH_SPORTS_REQUEST',
  FETCH_SPORTS_SUCCESS: 'FETCH_SPORTS_SUCCESS',
  FETCH_SPORTS_FAILURE: 'FETCH_SPORTS_FAILURE',
};

export default SportsActionTypes;
