const TransactionsActionTypes = {
  FETCH_TRANSACTIONS_REQUEST  : 'FETCH_TRANSACTIONS_REQUEST',
  FETCH_TRANSACTIONS_SUCCESS  : 'FETCH_TRANSACTIONS_SUCCESS',
  FETCH_TRANSACTIONS_FAILURE  : 'FETCH_TRANSACTIONS_FAILURE',
};

export default TransactionsActionTypes;
