const LiveHistoryTypes = {
  FETCH_LIVE_HISTORY_REQUEST  : 'FETCH_LIVE_HISTORY_REQUEST',
  FETCH_LIVE_HISTORY_SUCCESS  : 'FETCH_LIVE_HISTORY_SUCCESS',
  FETCH_LIVE_HISTORY_FAILURE  : 'FETCH_LIVE_HISTORY_FAILURE',
};

export default LiveHistoryTypes;
