const RecentLoginsActionTypes = {
  FETCH_CUSTOMER_LIST_REQUEST  : 'FETCH_CUSTOMER_LIST_REQUEST',
  FETCH_CUSTOMER_LIST_SUCCESS  : 'FETCH_CUSTOMER_LIST_SUCCESS',
  FETCH_CUSTOMER_LIST_FAILURE  : 'FETCH_CUSTOMER_LIST_FAILURE',
};

export default RecentLoginsActionTypes;
