const options = [
  { label: 'Football', value: 'football' },
  { label: 'Baseball', value: 'baseball' },
  { label: 'Breeders Cup', value: 'breeders cup' },
  { label: 'Closing Soon', value: 'closing soon' },
  { label: 'Esports', value: 'esports' },
  { label: 'Hockey', value: 'hockey' },
  { label: 'live', value: 'live' },
  { label: 'MMA', value: 'mma' },
  { label: 'Olympics', value: 'olympics' },
  { label: 'Other', value: 'other' },
  { label: 'Politics', value: 'politics' },
  { label: 'Racing', value: 'racing' },
  { label: 'Rugby', value: 'rugby' },
  { label: 'Soccer', value: 'soccer' },
  { label: 'Soccer - Minor', value: 'soccer - minor' },
  { label: 'Soccer Electronic', value: 'soccer electronic' },
  { label: 'Super Bowl LIV Props', value: 'super bowl liv props' },
  { label: 'Table Tennis', value: 'table tennis' },
  { label: 'Tennis', value: 'tennis' },
  { label: 'Virtual Sports', value: 'virtual sports' },
  { label: 'Zcontest header old', value: 'zcontest header old' },
];

export default options;
