const PendingWagersActionTypes = {
  FETCH_PENDING_WAGERS_REQUEST  : 'FETCH_PENDING_WAGERS_REQUEST',
  FETCH_PENDING_WAGERS_SUCCESS  : 'FETCH_PENDING_WAGERS_SUCCESS',
  FETCH_PENDING_WAGERS_FAILURE  : 'FETCH_PENDING_WAGERS_FAILURE',
};

export default PendingWagersActionTypes;
