const PositionContestsActionTypes = {
  FETCH_POSITION_CONTESTS_REQUEST  : 'FETCH_POSITION_CONTESTS_REQUEST',
  FETCH_POSITION_CONTESTS_SUCCESS  : 'FETCH_POSITION_CONTESTS_SUCCESS',
  FETCH_POSITION_CONTESTS_FAILURE  : 'FETCH_POSITION_CONTESTS_FAILURE',
};

export default PositionContestsActionTypes;
