const ClientAccountingTypes = {
  FETCH_CLIENT_ACCOUNTING_REQUEST  : 'FETCH_CLIENT_ACCOUNTING_REQUEST',
  FETCH_CLIENT_ACCOUNTING_SUCCESS  : 'FETCH_CLIENT_ACCOUNTING_SUCCESS',
  FETCH_CLIENT_ACCOUNTING_FAILURE  : 'FETCH_CLIENT_ACCOUNTING_FAILURE',
};

export default ClientAccountingTypes;
