const AdminBalanceActionTypes = {
  FETCH_ADMIN_BALANCE_REQUEST  : 'FETCH_ADMIN_BALANCE_REQUEST',
  FETCH_ADMIN_BALANCE_SUCCESS  : 'FETCH_ADMIN_BALANCE_SUCCESS',
  FETCH_ADMIN_BALANCE_FAILURE  : 'FETCH_ADMIN_BALANCE_FAILURE',
};

export default AdminBalanceActionTypes;
