const PendingBetsActionTypes = {
  FETCH_PENDING_BETS_REQUEST  : 'FETCH_PENDING_BETS_REQUEST',
  FETCH_PENDING_BETS_SUCCESS  : 'FETCH_PENDING_BETS_SUCCESS',
  FETCH_PENDING_BETS_FAILURE  : 'FETCH_PENDING_BETS_FAILURE',
};

export default PendingBetsActionTypes;
