const LiveProgramTypes = {
  FETCH_LIVE_PROGRAM_REQUEST  : 'FETCH_LIVE_PROGRAM_REQUEST',
  FETCH_LIVE_PROGRAM_SUCCESS  : 'FETCH_LIVE_PROGRAM_SUCCESS',
  FETCH_LIVE_PROGRAM_FAILURE  : 'FETCH_LIVE_PROGRAM_FAILURE',
};

export default LiveProgramTypes;
