const AccountActivityTypes = {
  FETCH_ACOUNT_ACTIVITY_REQUEST: 'FETCH_ACOUNT_ACTIVITY_REQUEST',
  FETCH_ACOUNT_ACTIVITY_SUCCESS: 'FETCH_ACOUNT_ACTIVITY_SUCCESS',
  FETCH_ACOUNT_ACTIVITY_FAILURE: 'FETCH_ACOUNT_ACTIVITY_FAILURE',
};

export default AccountActivityTypes;
