const ClientPendingActionTypes = {
  FETCH_CLIENT_PENDING_REQUEST  : 'FETCH_CLIENT_LIMITS_REQUEST',
  FETCH_CLIENT_PENDING_SUCCESS  : 'FETCH_CLIENT_LIMITS_SUCCESS',
  FETCH_CLIENT_PENDING_FAILURE  : 'FETCH_CLIENT_LIMITS_FAILURE',
};

export default ClientPendingActionTypes;
