const ActiveCustomersTypes = {
  FETCH_ACTIVE_CUSTOMERS_REQUEST: 'FETCH_ACTIVE_CUSTOMERS_REQUEST',
  FETCH_ACTIVE_CUSTOMERS_SUCCESS: 'FETCH_ACTIVE_CUSTOMERS_SUCCESS',
  FETCH_ACTIVE_CUSTOMERS_FAILURE: 'FETCH_ACTIVE_CUSTOMERS_FAILURE',
};

export default ActiveCustomersTypes;
