const ClientWagersTypes = {
  FETCH_CLIENT_WAGERS_REQUEST  : 'FETCH_CLIENT_WAGERS_REQUEST',
  FETCH_CLIENT_WAGERS_SUCCESS  : 'FETCH_CLIENT_WAGERS_SUCCESS',
  FETCH_CLIENT_WAGERS_FAILURE  : 'FETCH_CLIENT_WAGERS_FAILURE',
};

export default ClientWagersTypes;
