const AdminBalanceActionTypes = {
  FETCH_CLIENT_BALANCE_REQUEST  : 'FETCH_CLIENT_BALANCE_REQUEST',
  FETCH_CLIENT_BALANCE_SUCCESS  : 'FETCH_CLIENT_BALANCE_SUCCESS',
  FETCH_CLIENT_BALANCE_FAILURE  : 'FETCH_CLIENT_BALANCE_FAILURE',
};

export default AdminBalanceActionTypes;
