const MailActionTypes = {
  TOGGLE_MAIL: 'TOGGLE_MAIL',

  FETCH_INBOX_REQUEST: 'FETCH_INBOX_REQUEST',
  FETCH_INBOX_SUCCESS: 'FETCH_INBOX_SUCCESS',
  FETCH_INBOX_FAILURE: 'FETCH_INBOX_FAILURE',

  FETCH_SENT_REQUEST: 'FETCH_SENT_REQUEST',
  FETCH_SENT_SUCCESS: 'FETCH_SENT_SUCCESS',
  FETCH_SENT_FAILURE: 'FETCH_SENT_FAILURE',
};

export default MailActionTypes;
