const MailActionTypes = {
  TOGGLE_MAIL: 'TOGGLE_MAIL',

  FETCH_MESSAGES_REQUEST: 'FETCH_MESSAGES_REQUEST',
  FETCH_MESSAGES_SUCCESS: 'FETCH_MESSAGES_SUCCESS',
  FETCH_MESSAGES_FAILURE: 'FETCH_MESSAGES_FAILURE',

  FETCH_SENT_REQUEST: 'FETCH_SENT_REQUEST',
  FETCH_SENT_SUCCESS: 'FETCH_SENT_SUCCESS',
  FETCH_SENT_FAILURE: 'FETCH_SENT_FAILURE',

  DELETE_MESSAGE: 'DELETE_MESSAGE',
  DELETE_MESSAGES: 'DELETE_MESSAGES',
};

export default MailActionTypes;
