const ClienTransactionsTypes = {
  FETCH_CLIENT_TRANSACTIONS_REQUEST  : 'FETCH_CLIENT_TRANSACTIONS_REQUEST',
  FETCH_CLIENT_TRANSACTIONS_SUCCESS  : 'FETCH_CLIENT_TRANSACTIONS_SUCCESS',
  FETCH_CLIENT_TRANSACTIONS_FAILURE  : 'FETCH_CLIENT_TRANSACTIONS_FAILURE',
};

export default ClienTransactionsTypes;
