const PositionTodayActionTypes = {
  FETCH_POSITION_TODAY_REQUEST  : 'FETCH_POSITION_TODAY_REQUEST',
  FETCH_POSITION_TODAY_SUCCESS  : 'FETCH_POSITION_TODAY_SUCCESS',
  FETCH_POSITION_TODAY_FAILURE  : 'FETCH_POSITION_TODAY_FAILURE',
};

export default PositionTodayActionTypes;
