const SportsScheduleTypes = {
  FETCH_SPORTS_SCHEDULE_REQUEST: 'FETCH_SPORTS_SCHEDULE_REQUEST',
  FETCH_SPORTS_SCHEDULE_SUCCESS: 'FETCH_SPORTS_SCHEDULE_SUCCESS',
  FETCH_SPORTS_SCHEDULE_FAILURE: 'FETCH_SPORTS_SCHEDULE_FAILURE',
};

export default SportsScheduleTypes;
