const WeeklyFiguresActionTypes = {
  FETCH_WEEKLY_FIGURES_REQUEST  : 'FETCH_WEEKLY_FIGURES_REQUEST',
  FETCH_WEEKLY_FIGURES_SUCCESS  : 'FETCH_WEEKLY_FIGURES_SUCCESS',
  FETCH_WEEKLY_FIGURES_FAILURE  : 'FETCH_WEEKLY_FIGURES_FAILURE',
};

export default WeeklyFiguresActionTypes;
